# Generated by Django 5.2.17 on 2026-09-05 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=180)),
                ('institution_type', models.CharField(choices=[('bank', 'Bank'), ('sacco', 'SACCO')], max_length=8)),
                ('account_name', models.CharField(max_length=180)),
                ('account_last_four', models.CharField(blank=True, max_length=4)),
                ('currency', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD'), ('KES', 'KES')], default='UGX', max_length=3)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('interest_period', models.CharField(choices=[('annual', 'Per year'), ('monthly', 'Per month')], default='annual', max_length=8)),
                ('minimum_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('terms_updated_on', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institution_name', 'account_name', 'id'],
            },
        ),
    ]
