# Generated by Django 5.2.17 on 2026-09-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_partneraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraccount',
            name='terms_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='share_sacco_insights',
            field=models.BooleanField(default=False),
        ),
    ]
