# Generated by Django 5.2.17 on 2026-09-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recoveryratelimit_passwordresetchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetchallenge',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecoveryRateLimit',
        ),
        migrations.DeleteModel(
            name='PasswordResetChallenge',
        ),
    ]
